project_name: mracek
before:
  hooks: []
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs'
      - '^test'
      - '^chore'
      - '^style'
      - '^ci'
      - '^Merge pull request'
  groups:
    - title: 'New Features'
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: 'Bug fixes'
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 10
    - title: Other work
      order: 999
release:
  github:
    owner: mchlumsky
    name: mracek
nfpms:
  - file_name_template: '{{ .ConventionalFileName }}'
    id: packages
    homepage:  https://github.com/mchlumsky/mracek
    description: Small command line tool to manage your OpenStack configuration files
    maintainer: Martin Chlumsky <martin.chlumsky@gmail.com>
    license: MIT
    contents:
      - src: ./completions/mracek.bash
        dst: /etc/bash_completion.d/mracek
      - src: ./completions/mracek.fish
        dst: /usr/share/fish/completions/mracek.fish
      - src: ./completions/mracek.zsh
        dst: /usr/local/share/zsh/site-functions/_mracek
    formats:
      - deb
      - rpm
publishers:
  - name: fury.io
    ids:
      - packages
    cmd: ./scripts/fury-upload.sh {{ .ArtifactName }}