# https://taskfile.dev

version: '3'

tasks:
  default:
    cmds:
      - task --list-all

  lint:
    cmds:
      - go tool -modfile go.golangci-lint.mod golangci-lint run

  all-tests:
    deps:
      - lint
      - test
      - test-release

  test:
    env:
      CGO_ENABLED: 1
    cmds:
      - go test -cover -v -race $(go list ./...)

  build:
    cmds:
      - go tool -modfile go.goreleaser.mod goreleaser build --skip=validate --clean --snapshot

  test-release:
    cmds:
      - go tool -modfile go.goreleaser.mod goreleaser release --skip=validate --skip=publish --clean --snapshot

  release:
    vars:
      # Disable shallow cloning so that goreleaser can diff between tags to
      # generate a changelog.
      GIT_DEPTH: 0
    cmds:
      - go tool -modfile go.goreleaser.mod goreleaser release --clean

  coverage:
    cmds:
      - go test -v -cover -coverprofile=c.out ./...
      - go tool cover -func=c.out
      - rm c.out

  demo:
    env:
      MRACEK_OS_CONFIG_DIR: ./
    dir: assets/
    cmds:
      - echo $MRACEK_OS_CONFIG_DIR
      - echo $PWD
      - go tool -modfile ../go.vhs.mod vhs demo.tape
      - rm clouds.yaml
      - rm secure.yaml

  smoke-tests-demo:
    dir: assets/
    cmds:
      - go tool -modfile ../go.vhs.mod vhs smoke-tests.tape
